### ISSUE TITLE
Error trying running the first example

### ISSUE THREAD

**Issue by vteran93** [influxdata/influxdb-client-python#127]
Hi, I was trying to execute the first example in the readme, I think I did configure chronograph and influx correctly because I was able to run queries with the token using the curl tool, however when I try to run the example, I am getting this traceback: 

```
> /home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/urllib3/poolmanager.py(337)urlopen()
-> response = conn.urlopen(method, u.request_uri, **kw)
(Pdb) c
Traceback (most recent call last):
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7faee0e34690>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 26, in <module>
    tables =  query_api.query(my_query)
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/influxdb_client/client/query_api.py", line 69, in query
    async_req=False, _preload_content=False, _return_http_data_only=False)
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/influxdb_client/service/query_service.py", line 246, in post_query
    (data) = self.post_query_with_http_info(**kwargs)  # noqa: E501
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/influxdb_client/service/query_service.py", line 335, in post_query_with_http_info
    collection_formats=collection_formats)
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/influxdb_client/api_client.py", line 339, in call_api
    _preload_content, _request_timeout)
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/influxdb_client/api_client.py", line 170, in __call_api
    _request_timeout=_request_timeout)
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/influxdb_client/api_client.py", line 382, in request
    body=body)
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/influxdb_client/rest.py", line 278, in POST
    body=body)
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/influxdb_client/rest.py", line 170, in request
    headers=headers)
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/urllib3/request.py", line 80, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/urllib3/poolmanager.py", line 337, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/urllib3/connectionpool.py", line 765, in urlopen
    **response_kw
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/urllib3/connectionpool.py", line 765, in urlopen
    **response_kw
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/urllib3/connectionpool.py", line 765, in urlopen
    **response_kw
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/victor.teran/.local/share/virtualenvs/influx-testing-ISz8qS6h/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8886): Max retries exceeded with url: /api/v2/query?org=sdc_testing (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faee0e34690>: Failed to establish a new connection: [Errno 111] Connection refused'))

```

This is the command that I used in the curl tool to be sure if the token configuration was ok.
```
	curl -XPOST localhost:8086/api/v2/query  \
	  -H 'Accept:application/csv' \
	  -H 'Authorization: Bearer myToken' \
	  -H 'Content-type:application/vnd.flux' \
	  -d 'from(bucket:"telegraf")
		|> range(start:-5m)
		|> filter(fn:(r) => r._measurement == "cpu")'  
```

**Comment by bednar** [comment]
Hi @vteran93,

If I understand correctly than you trying connect to InfluxDB 1.8. It is right?

The InfluxDB 1.8 uses `username` and `password` separated by a colon for authorization.


> Authorization: In InfluxDB 2.0 uses API Tokens to access the platform and all its capabilities. InfluxDB v1.x uses a username and password combination when accessing the HTTP APIs. Use the Token schema to provide your InfluxDB 1.x username and password separated by a colon (:). For example: Authorization: Token username:password.

see [InfluxDB 2.0 API compatibility endpoints](https://docs.influxdata.com/influxdb/v1.8/tools/api/#influxdb-2-0-api-compatibility-endpoints)

We have an example for connecting to InfluxDB 1.8 - see [influxdb_18_example.py](https://github.com/influxdata/influxdb-client-python/blob/master/examples/influxdb_18_example.py).

Regards

**Comment by vteran93** [comment]
Thanks @bednar , It worked. I think we could close the ticket :-)
