### ISSUE TITLE
Health check returns "invalid name", despite connection working

### ISSUE THREAD

**Issue by MatinF** [influxdata/influxdb-client-python#166]
I'm using a simple script to write dataframes to InfluxDB v2.0 (cloud starter) using the API.

As part of my script, I wish to check the health of my connection - and break the script if the health check does not pass.

I've used the below code for this purpose:

```
from influxdb_client import InfluxDBClient, Point, WriteOptions
from influxdb_client.client.write_api import SYNCHRONOUS

# initialize client and write to InfluxDB
client = InfluxDBClient(url=inputs.influx_url, token=inputs.token, org=inputs.org_id, debug=False)
print(client.health())
```

This worked previously and it would return the message `pass` when the connection worked, but for some reason I am now getting the following health message regardless of whether the connection works or not:

```
{'checks': None,
 'commit': None,
 'message': 'Invalid value for `name`, must not be `None`',
 'name': 'influxdb',
 'status': 'fail',
 'version': None}
```

I'm using the latest version `1.11.0`. Please let me know if I'm missing something here.

**Comment by bednar** [comment]
Hi @MatinF,

It is caused by https://github.com/influxdata/influxdb/issues/19357. 

As a workaround you could use something like:
```python
client = InfluxDBClient(url=inputs.influx_url, token=inputs.token, org=inputs.org_id, debug=False)
print(client.api_client.request("GET", f'{influx_cloud_url}/ping').status)
```

Regards

**Comment by MatinF** [comment]
Thanks for the fast reply @bednar. I tried the below:

```
status = client.api_client.request("GET", f"{inputs.influx_url}/ping").status
print(status)
```
In my case, this returns `204` - but it does so regardless of whether the connection works or not. 

For example, if I misspell the org ID or token, I still get a `204`. What I was hoping to achieve was to "capture" a case where one or more of the credential inputs (url, token, org_id) are incorrect. Is there a way to use your concept that would achieve this?

**Comment by bednar** [comment]
Yeah, try this:

```python
print(client.query_api().query("buckets()"))
```

**Comment by MatinF** [comment]
Hi again,

I tried using that - I think it works in the sense that I can e.g. use it as below:

```
client = InfluxDBClient(url=inputs.influx_url, token=inputs.token, org=inputs.org_id, debug=False)

try:
    test = client.query_api().query("buckets()")
except Exception as err:
    print(err)
```
If I set it up without the ``try`` statement, the code simply breaks in case there is an issue and I get below response (e.g. in the case where the token is wrong):
```
Traceback (most recent call last):
  File "C:\Users\marti\Documents\dashboard-writer\dashboard-writer\main.py", line 64, in <module>
    process_data_and_write()
  File "C:\Users\marti\Documents\dashboard-writer\dashboard-writer\main.py", line 56, in process_data_and_write
    write_influx(device_id, df_signal)
  File "C:\Users\marti\Documents\dashboard-writer\dashboard-writer\utils.py", line 19, in write_influx
    test = client.query_api().query("buckets()")
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\influxdb_client\client\query_api.py", line 77, in query
    async_req=False, _preload_content=False, _return_http_data_only=False)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\influxdb_client\service\query_service.py", line 260, in post_query
    (data) = self.post_query_with_http_info(**kwargs)  # noqa: E501
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\influxdb_client\service\query_service.py", line 355, in post_query_with_http_info
    urlopen_kw=urlopen_kw)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\influxdb_client\api_client.py", line 345, in call_api
    _preload_content, _request_timeout, urlopen_kw)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\influxdb_client\api_client.py", line 174, in __call_api
    _request_timeout=_request_timeout, **urlopen_kw)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\influxdb_client\api_client.py", line 392, in request
    **urlopen_kw)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\influxdb_client\rest.py", line 309, in POST
    **urlopen_kw)
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\influxdb_client\rest.py", line 252, in request
    raise ApiException(http_resp=r)
influxdb_client.rest.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Date': 'Wed, 28 Oct 2020 11:26:45 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '55', 'Connection': 'keep-alive', 'x-platform-error-code': 'unauthorized', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains'})
HTTP response body: b'{"code":"unauthorized","message":"unauthorized access"}'
```

What I would ideally like would be to help users by providing more informative error handling. For example, I would like to be able to get the ``unauthorized`` result in a variable that I can then test based on to print a warning message for the user to review their token. However, I struggle to find the best way to extract detailed information from the response. Any inputs on this would be great.

**Comment by bednar** [comment]
Currently not, but it is a good point to improvement. Meanwhile you could use something like:

```python
def reason_from_body(ae: ApiException):
    if ae.body:
        import json
        try:
            return json.loads(ae.body)["message"]
        except Exception as pe:
            import logging
            logging.debug(f"Cannot parse error response to JSON: {ae.body}, {pe}")
            return ae.body

    # Http Status
    return ae.reason


try:
    test = client.query_api().query(f'from(bucket:"{inputs.influx_bucket}") |> range(start: -10m)')
except ApiException as e:
    print(reason_from_body(e))
```

**Comment by MatinF** [comment]
Thanks, I'll try that out

**Comment by el-stinjo** [comment]
I have the exact same situation
