### ISSUE TITLE
Create database using infludb_client in Influxdb1.8.*

### ISSUE THREAD

**Issue by amaljithkuttamath** [influxdata/influxdb-client-python#186]
__Proposal:__

__Current behavior:__
Describe what currently happens.

```python
  self.client= InfluxDBClient(url='http://localhost:8086', token=f'{username}:{password}', org='-')
  self.client.buckets_api().create_bucket(bucket = "hht2.autogen")
```

```shell
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '1.8.3', 'Date': 'Mon, 18 Jan 2021 11:46:36 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found

Traceback (most recent call last):
  File "/Users/ak/arc_mvp/arc/arcHelpers/src/hInflux2Manager.py", line 81, in jsontoInflux
    self.client.buckets_api().create_bucket(bucket = "hht2.autogen")
  File "/Users/ak/arc_mvp/venv/lib/python3.8/site-packages/influxdb_client/client/bucket_api.py", line 52, in create_bucket
    return self._buckets_service.post_buckets(post_bucket_request=bucket)
  File "/Users/ak/arc_mvp/venv/lib/python3.8/site-packages/influxdb_client/service/buckets_service.py", line 1262, in post_buckets
    (data) = self.post_buckets_with_http_info(post_bucket_request, **kwargs)  # noqa: E501
  File "/Users/ak/arc_mvp/venv/lib/python3.8/site-packages/influxdb_client/service/buckets_service.py", line 1334, in post_buckets_with_http_info
    return self.api_client.call_api(
  File "/Users/ak/arc_mvp/venv/lib/python3.8/site-packages/influxdb_client/api_client.py", line 340, in call_api
    return self.__call_api(resource_path, method,
  File "/Users/ak/arc_mvp/venv/lib/python3.8/site-packages/influxdb_client/api_client.py", line 170, in __call_api
    response_data = self.request(
  File "/Users/ak/arc_mvp/venv/lib/python3.8/site-packages/influxdb_client/api_client.py", line 385, in request
    return self.rest_client.POST(url,
  File "/Users/ak/arc_mvp/venv/lib/python3.8/site-packages/influxdb_client/rest.py", line 302, in POST
    return self.request("POST", url,
  File "/Users/ak/arc_mvp/venv/lib/python3.8/site-packages/influxdb_client/rest.py", line 252, in request
    raise ApiException(http_resp=r)
influxdb_client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '1.8.3', 'Date': 'Mon, 18 Jan 2021 11:46:36 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found
```

__Desired behavior:__
Should create a database.

__Alternatives considered:__
1. Using influxdb2.0
2. bucket = f'{database}/{retention_policy}'

__Use case:__
Been using 1.8.3 since its release. [not really using anything T,K from tick stack]

**Comment by bednar** [comment]
Hi @amaljithkuttamath,

the `BucketApi` is not compatible with `1.8`. See docs about 1.x compatibility here: https://docs.influxdata.com/influxdb/cloud/reference/api/influxdb-1x/

Regards
