### ISSUE TITLE
influxdb_client.rest.ApiException: (0) Reason: SSLError [Errno 20] Not a directory

### ISSUE THREAD

**Issue by reinhard-brandstaedter** [influxdata/influxdb-client-python#191]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. executing a python metric post within python 3.6.6 virtual environment
2. 

__Expected behavior:__
Describe what you expected to happen.
Trying to write datapoints to InfluxDB cloud:
```
write_api = client.write_api(write_options=SYNCHRONOUS)
influxline = "hostunits,{}={} hostunits={:.2f}".format(self.hutag,split,value)
write_api.write(bucket, org, influxline)
```

__Actual behavior:__
The write_api.write call fails with a SSLError:
```
Traceback (most recent call last):
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/util/ssl_.py", line 319, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
NotADirectoryError: [Errno 20] Not a directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/rest.py", line 221, in request
    **urlopen_kw)
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/poolmanager.py", line 324, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/util/retry.py", line 344, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/util/ssl_.py", line 321, in ssl_wrap_socket
    raise SSLError(e)
urllib3.exceptions.SSLError: [Errno 20] Not a directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/ruxit/plugin_state_machine.py", line 674, in _query_plugin
    self._plugin_run_data.plugin_instance._query_internal(**self._plugin_run_data.plugin_args)
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/ruxit/api/base_plugin.py", line 452, in _query_internal
    return self.query(**kwargs)
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/missingmetrics.py", line 54, in query
    self.getHostUnits()
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/missingmetrics.py", line 125, in getHostUnits
    write_api.write(bucket, org, influxline)
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/client/write_api.py", line 251, in write
    results = list(map(write_payload, payloads.items()))
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/client/write_api.py", line 249, in write_payload
    return self._post_write(_async_req, bucket, org, final_string, payload[0])
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/client/write_api.py", line 369, in _post_write
    **kwargs)
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/service/write_service.py", line 64, in post_write
    (data) = self.post_write_with_http_info(org, bucket, body, **kwargs)  # noqa: E501
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/service/write_service.py", line 183, in post_write_with_http_info
    urlopen_kw=urlopen_kw)
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/api_client.py", line 345, in call_api
    _preload_content, _request_timeout, urlopen_kw)
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/api_client.py", line 174, in __call_api
    _request_timeout=_request_timeout, **urlopen_kw)
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/api_client.py", line 392, in request
    **urlopen_kw)
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/rest.py", line 309, in POST
    **urlopen_kw)
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/rest.py", line 238, in request
    raise ApiException(status=0, reason=msg)
influxdb_client.rest.ApiException: (0)
Reason: SSLError
[Errno 20] Not a directory

2021-01-28 17:45:02.882 UTC ERROR   [Python][15052339058944823227][Hostunit Consumption][140228056573696][ThreadPoolExecutor-0_0] - [set_full_status] (0)
Reason: SSLError
[Errno 20] Not a directory
Traceback (most recent call last):
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/util/ssl_.py", line 319, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
NotADirectoryError: [Errno 20] Not a directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/rest.py", line 221, in request
    **urlopen_kw)
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/poolmanager.py", line 324, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/util/retry.py", line 344, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/site-packages/urllib3/util/ssl_.py", line 321, in ssl_wrap_socket
    raise SSLError(e)
urllib3.exceptions.SSLError: [Errno 20] Not a directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/ruxit/plugin_state_machine.py", line 340, in _execute_next_task
    self._query_plugin()
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/ruxit/plugin_state_machine.py", line 674, in _query_plugin
    self._plugin_run_data.plugin_instance._query_internal(**self._plugin_run_data.plugin_args)
  File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/ruxit/api/base_plugin.py", line 452, in _query_internal
    return self.query(**kwargs)
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/missingmetrics.py", line 54, in query
    self.getHostUnits()
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/missingmetrics.py", line 125, in getHostUnits
    write_api.write(bucket, org, influxline)
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/client/write_api.py", line 251, in write
    results = list(map(write_payload, payloads.items()))
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/client/write_api.py", line 249, in write_payload
    return self._post_write(_async_req, bucket, org, final_string, payload[0])
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/client/write_api.py", line 369, in _post_write
    **kwargs)
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/service/write_service.py", line 64, in post_write
    (data) = self.post_write_with_http_info(org, bucket, body, **kwargs)  # noqa: E501
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/service/write_service.py", line 183, in post_write_with_http_info
    urlopen_kw=urlopen_kw)
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/api_client.py", line 345, in call_api
    _preload_content, _request_timeout, urlopen_kw)
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/api_client.py", line 174, in __call_api
    _request_timeout=_request_timeout, **urlopen_kw)
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/api_client.py", line 392, in request
    **urlopen_kw)
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/rest.py", line 309, in POST
    **urlopen_kw)
  File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.missingmetrics/influxdb_client/rest.py", line 238, in request
    raise ApiException(status=0, reason=msg)
influxdb_client.rest.ApiException: (0)
Reason: SSLError
[Errno 20] Not a directory
```

Research recommended that this might have to do due to missing python certifi package, which is however present in this virtual environment.

__Specifications:__
 - Client Version: python client in a virtual environment: certifi-2020.12.5, influxdb_client-1.13.0
 - InfluxDB Version: InfluxDBCloud
 - Platform: Linux, python venv 3.6.6

**Comment by bednar** [comment]
Hi @reinhard-brandstaedter,

thanks for using our client.

I've tried your configuration in Docker via:

```console
# Start Docker
docker run -it -w /home python:3.6.6 bash

# Setup Virtual Env and install dependencies
python -m venv venv
source venv/bin/activate
pip install certifi
pip install influxdb-client==1.13.0

# Download and Run InfluxDB Cloud example
wget https://raw.githubusercontent.com/influxdata/influxdb-client-python/master/examples/influx_cloud.py
python influx_cloud.py
```

and everything works fine.

How do you initialize the client?

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.

**Comment by reinhard-brandstaedter** [comment]
I figured out that this has indeed nothing to do with the influx-client.
The client requires the ca certificates that ship with e.g. certifi.
However in this case (special venv executed as part of a plugin framework) the cacerts are not directly located in the filesystem but in a zip file (/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip).
I have no idea how a normal python program would be able to load the cacerts from within a zip file - but this is where the error stems from.

After placing the cacert file in a real directory and pointing the INflux client to it, everything works fine:
```
client = InfluxDBClient(url=influxdb, token=token, ssl_ca_cert="/opt/certifi/cacert.pem")
```

**Comment by bednar** [comment]
@reinhard-brandstaedter thanks for clarification. It will be useful for other users
