### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] 

### ISSUE THREAD

**Issue by srbpavel** [influxdata/influxdb-client-python#244]
dear, please how can i debug more for ssl_verification?
[or is that problem of my current python version as with curl i am succesfull]

- python3                           3.7.3-1
- Debian 4.19.0-16-cloud-amd64
- influxdb2-2.0.6-amd64.deb
- pip3 package / influxdb-client   1.16.0

cert settings in my config [generated via certbot]: 
I_SSL_CA_CERT = '/etc/letsencrypt/live/MY_DOMAIN/fullchain.pem' 

client call:
client = InfluxDBClient(url = i_host,
                        token = i_token,
                        org = i_org,
                        debug = True, 
                        verify_ssl = True, 
                        ssl_ca_cert = i_ssl_ca_cert)

output:

Traceback (most recent call last):
  File "/home/conan/.local/lib/python3.7/site-packages/influxdb_client/rest.py", line 185, in request
    **urlopen_kw)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 323, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 343, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/conan/.local/lib/python3.7/site-packages/influxdb_client/client/query_api.py", line 77, in query
    async_req=False, _preload_content=False, _return_http_data_only=False)
  File "/home/conan/.local/lib/python3.7/site-packages/influxdb_client/service/query_service.py", line 260, in post_query
    (data) = self.post_query_with_http_info(**kwargs)  # noqa: E501
  File "/home/conan/.local/lib/python3.7/site-packages/influxdb_client/service/query_service.py", line 355, in post_query_with_http_info
    urlopen_kw=urlopen_kw)
  File "/home/conan/.local/lib/python3.7/site-packages/influxdb_client/api_client.py", line 345, in call_api
    _preload_content, _request_timeout, urlopen_kw)
  File "/home/conan/.local/lib/python3.7/site-packages/influxdb_client/api_client.py", line 174, in __call_api
    _request_timeout=_request_timeout, **urlopen_kw)
  File "/home/conan/.local/lib/python3.7/site-packages/influxdb_client/api_client.py", line 392, in request
    **urlopen_kw)
  File "/home/conan/.local/lib/python3.7/site-packages/influxdb_client/rest.py", line 307, in POST
    **urlopen_kw)
  File "/home/conan/.local/lib/python3.7/site-packages/influxdb_client/rest.py", line 236, in request
    raise ApiException(status=0, reason=msg)
influxdb_client.rest.ApiException: (0)
Reason: SSLError
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1056)

but manual verification looks all right:

openssl x509 -in cert1.pem -noout -issuer
issuer=C = US, O = Let's Encrypt, CN = R3

openssl x509 -in chain1.pem -noout -subject
subject=C = US, O = Let's Encrypt, CN = R3

openssl verify -untrusted chain1.pem cert1.pem
cert1.pem: OK

openssl crl2pkcs7 -nocrl -certfile fullchain1.pem | openssl pkcs7 -print_certs -noout
subject=CN = MY_DOMAIN

issuer=C = US, O = Let's Encrypt, CN = R3

subject=C = US, O = Let's Encrypt, CN = R3

issuer=C = US, O = Internet Security Research Group, CN = ISRG Root X1

subject=C = US, O = Internet Security Research Group, CN = ISRG Root X1

issuer=O = Digital Signature Trust Co., CN = DST Root CA X3

am i missing something? 

thank you, pavel

**Comment by srbpavel** [comment]
edit

**Comment by bednar** [comment]
Hi @srbpavel,

thanks for using our client.

Can you please check your `ca_cert` by:

```python
import urllib3

conn = urllib3.connection_from_url(i_host, ca_certs=i_ssl_ca_cert)
r = conn.urlopen('HEAD', '/health')
print(r.headers)

```
?

Regards

**Comment by srbpavel** [comment]
ahoj , here is the output:

- i know about the below warning, when using your client to read data [(maybe that can be the cause ?)]
- the host is on local domain as for test behind firewall

i_host
'https://ruth:8086'

>>> import urllib3
>>> conn = urllib3.connection_from_url(i_host, ca_certs=i_ssl_ca_cert)
>>> r = conn.urlopen('HEAD', '/health')
/usr/lib/python3/dist-packages/urllib3/connection.py:362: SubjectAltNameWarning: Certificate for ruth has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
>>> print(r.headers)
HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'Date': 'Fri, 07 May 2021 07:40:21 GMT', 'Content-Length': '136'})

pavel

**Comment by bednar** [comment]
> ahoj , here is the output:
> 
> * i know about the below warning, when using your client to read data [(maybe that can be the cause ?)]

Probably not.

> * the host is on local domain as for test behind firewall

Maybe there is a problem with domain of your certificate. Your certificate has `CN=MY_DOMAIN`, but you are connecting to 'https://ruth:8086'.

> 
> i_host
> 'https://ruth:8086'
> 
> > > > import urllib3
> > > > conn = urllib3.connection_from_url(i_host, ca_certs=i_ssl_ca_cert)
> > > > r = conn.urlopen('HEAD', '/health')
> > > > /usr/lib/python3/dist-packages/urllib3/connection.py:362: SubjectAltNameWarning: Certificate for ruth has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See [urllib3/urllib3#497](https://github.com/urllib3/urllib3/issues/497) for details.)
> > > > SubjectAltNameWarning
> > > > print(r.headers)
> > > > HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'Date': 'Fri, 07 May 2021 07:40:21 GMT', 'Content-Length': '136'})
> 
> pavel

It looks like that connection via SSL is correct. Can you enable cert verification by:

```python
import ssl

import urllib3

conn = urllib3.connection_from_url(i_host, ca_certs=i_ssl_ca_cert, cert_reqs=ssl.CERT_REQUIRED)
r = conn.urlopen('HEAD', '/health')
print(r.headers)

```
?

**Comment by srbpavel** [comment]
my appology for the last comment, i get confused, here is the valid info:

- i am getting error at production server ( i badly look at test one)

i_host
'https://xxxxx.srbpavel.cz:8086'
>>> i_ssl_ca_cert
'/etc/letsencrypt/live/xxx.srbpavel.cz/fullchain.pem'
>>> 
>>> 
>>> import ssl
>>> import urllib3
>>> conn = urllib3.connection_from_url(i_host, ca_certs=i_ssl_ca_cert)
>>> 
>>> conn = urllib3.connection_from_url(i_host, ca_certs=i_ssl_ca_cert, cert_reqs=ssl.CERT_REQUIRED)
>>> r = conn.urlopen('HEAD', '/health')
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='xxxxx.srbpavel.cz', port=8086): Max retries exceeded with url: /health (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1056)')))

**Comment by srbpavel** [comment]
as it is not in your client code, you can close my question. i will investigate and post my results later, when done.

- tests with python 3.8 or 3.9 also did not help.
- what cert authority are you using to succeed with verify=True 

thank you, pavel
