### ISSUE TITLE
Requesting data as a dataframe leads sometimes to index out of range error

### ISSUE THREAD

**Issue by karlTGA** [influxdata/influxdb-client-python#268]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Request a great number (~100.000 rows) of points with `query_data_frame`. 
```
client = InfluxDBClient.from_env_properties()
api = client.query_api()
dataframe = api.query_data_frame(
    query="""
    from(bucket: "Bucket")
        |> range(start: 2017-01-01T00:00:00+01:00, stop: 2018-12-28T23:59:59+01:00)
        |> filter(fn: (r) => r["_measurement"] == "Measurement")
        |> filter(fn: (r) => r["_field"] == "Field")
        |> aggregateWindow(every: 5m, fn: mean, createEmpty: true)
        |> yield(name: "mean")
"""
)
```

__Expected behavior:__
Get the points as a data frame.

__Actual behavior:__
Get a error message: 
```
Traceback (most recent call last):
  File "data_operation_rating/test.py", line 51, in <module>
    dataframe = api.query_data_frame(
  File "/Users/***/Library/Caches/pypoetry/virtualenvs/analysen-nL-C86cZ-py3.8/lib/python3.8/site-packages/influxdb_client/client/query_api.py", line 140, in query_data_frame
    _dataFrames = list(_generator)
  File "/Users/***/Library/Caches/pypoetry/virtualenvs/analysen-nL-C86cZ-py3.8/lib/python3.8/site-packages/influxdb_client/client/flux_csv_parser.py", line 71, in generator
    yield from parser._parse_flux_response()
  File "/Users/***/Library/Caches/pypoetry/virtualenvs/analysen-nL-C86cZ-py3.8/lib/python3.8/site-packages/influxdb_client/client/flux_csv_parser.py", line 156, in _parse_flux_response
    flux_record = self.parse_record(table_index - 1, table, csv)
  File "/Users/***/Library/Caches/pypoetry/virtualenvs/analysen-nL-C86cZ-py3.8/lib/python3.8/site-packages/influxdb_client/client/flux_csv_parser.py", line 199, in parse_record
    str_val = csv[fluxColumn.index + 1]
IndexError: list index out of range   
```

On the Server Side I registered that error message:
```
ts=2021-06-14T11:00:16.860094Z lvl=info msg="Error writing response to client" log_id=0UjSLdX0000 handler=flux error="csv encoder error: write tcp 172.19.0.10:8086->172.19.0.2:37554: i/o timeout"
```

__Specifications:__
 - Client Version: 1.18.0
 - InfluxDB Version: 2.0.7
 - Platform: MacOS and Windows 10

**Comment by bednar** [comment]
Hi @karlTGA,

thanks for using our client. 

It looks like HTTP timeout error. You can increase timeout by `timeout` parameter:

```python
# set timeout to 30 sec
InfluxDBClient(url="http://localhost:8086", token="my-token", org="my-org", timeout=30_000)
```


Regards

**Comment by karlTGA** [comment]
Hi @bednar ,

thank you for the fast response. You'r right. It is a timeout problem. But not on the client side. On the server side the timeout was set with 30s for reads and that was not enough. I think it is a bandwidth problem of our network, but I have to solve that myself.😅

Can you tell my, why the client don't recognize the unclean end of the request and tries to parse a broken message?

Nice regards

**Comment by bednar** [comment]
> Hi @bednar ,
> 
> thank you for the fast response. You'r right. It is a timeout problem. But not on the client side. On the server side the timeout was set with 30s for reads and that was not enough. I think it is a bandwidth problem of our network, but I have to solve that myself.😅
> 

Try to enable GZIP compression by `enable_gzip` parameter:

```python
InfluxDBClient(url="http://localhost:8086", token="my-token", org="my-org", enable_gzip=True)
```

> Can you tell my, why the client don't recognize the unclean end of the request and tries to parse a broken message?
> 

Currently, I don't know, because I am not able to simulate this behaviour. Can you share the debug log from client?

```python
InfluxDBClient(url="http://localhost:8086", token="my-token", org="my-org", debug=True)
```

**Comment by karlTGA** [comment]
Yeah sure, maybe I can help. At first the logs with the debug flag. I tried it like you suggested but that change nothing, so I set the debug flag manual for the loggers `urllib3` and `influxdb_client`. Urlib logs then some messages but the influx is still quite. 

```
Start: 2021-06-14T16:14:24.260855 
2021-06-14 16:14:24,261 - urllib3.util.retry - DEBUG - Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2021-06-14 16:14:24,261 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): server_url.org
/Users/******/Library/Caches/pypoetry/virtualenvs/analysen-nL-C86cZ-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py:853: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn((
2021-06-14 16:14:24,588 - urllib3.connectionpool - DEBUG - https://server_url.org:443 "POST /api/v2/query?org=8b65e6860f5ad34a HTTP/1.1" 200 None
End: 2021-06-14T16:14:44.585959 
Traceback (most recent call last):
  File "/Users/******/Projects/repo/010-Analysen/data_operation_rating/test.py", line 87, in <module>
    raise err
  File "/Users/******/Projects/repo/010-Analysen/data_operation_rating/test.py", line 75, in <module>
    dataframe = api.query_data_frame(
  File "/Users/******/Library/Caches/pypoetry/virtualenvs/analysen-nL-C86cZ-py3.8/lib/python3.8/site-packages/influxdb_client/client/query_api.py", line 140, in query_data_frame
    _dataFrames = list(_generator)
  File "/Users/******/Library/Caches/pypoetry/virtualenvs/analysen-nL-C86cZ-py3.8/lib/python3.8/site-packages/influxdb_client/client/flux_csv_parser.py", line 71, in generator
    yield from parser._parse_flux_response()
  File "/Users/******/Library/Caches/pypoetry/virtualenvs/analysen-nL-C86cZ-py3.8/lib/python3.8/site-packages/influxdb_client/client/flux_csv_parser.py", line 156, in _parse_flux_response
    flux_record = self.parse_record(table_index - 1, table, csv)
  File "/Users/******/Library/Caches/pypoetry/virtualenvs/analysen-nL-C86cZ-py3.8/lib/python3.8/site-packages/influxdb_client/client/flux_csv_parser.py", line 199, in parse_record
    str_val = csv[fluxColumn.index + 1]
IndexError: list index out of range  
```

When I enable gzip, the answer ist only a empty data frame:

```
2021-06-14 16:31:15,012 - urllib3.util.retry - DEBUG - Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2021-06-14 16:31:15,012 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): timeseries.gewv.iet.mw.tu-dresden.de
/Users/karlwolffgang/Library/Caches/pypoetry/virtualenvs/analysen-nL-C86cZ-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py:853: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn((
2021-06-14 16:31:15,455 - urllib3.connectionpool - DEBUG - https://timeseries.gewv.iet.mw.tu-dresden.de:443 "POST /api/v2/query?org=8b65e6860f5ad34a HTTP/1.1" 200 None
Empty DataFrame
Columns: []
Index: []  
```

**Comment by bednar** [comment]
Hi @karlTGA, 

I am able to simulate the `"csv encoder error: write tcp 192.168.0.2:8086->192.168.0.1:63286: i/o timeout"` on the server side. But on the client side the `query_api` correctly report: `"Connection broken: IncompleteRead(1112 bytes read, 2984 more expected)"`.

Which version of the `python and` `urllib3` do you use? 

My testing enviroment:
- python: 3.8.2
- urllib3: 1.26.3
- MacOS: 11.5.2

```python
from influxdb_client import InfluxDBClient

with InfluxDBClient(url="http://localhost:8086", token="my-token", org="my-org", debug=False) as client:
    query_api = client.query_api()
    
    query = '''
from(bucket: "my-bucket")
  |> range(start: 0)
  |> filter(fn: (r) => r["_measurement"] == "data_frame_100")
  |> filter(fn: (r) => r["_field"] == "humid")
  |> aggregateWindow(every: 5m, fn: mean, createEmpty: true)
  |> yield(name: "mean")'''
    
    data_frame = query_api.query_data_frame(query)
    print(data_frame)

```

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
