### ISSUE TITLE
influxdb_client used with pytest-influxdb 

### ISSUE THREAD

**Issue by rburchdish** [influxdata/influxdb-client-python#286]
I am running into an issue after updating my influxdb version to 2.0.7.

The issue is that my write_point queries are no longer working with my pytest code. More so, I am actually unable to connect to my influxdb instance within a pytest script. 

__Steps to reproduce:__
The code looks like such:
```python
@pytest.fixture(scope="session", autouse=True)
def client_setup(influxdb_url, token, username, password, org, database):  # These values are coming from a conftest.py file
    new_client = InfluxDBClient(url=influxdb_url, token=token, username=username, password=password, org=org)
    write_api = new_client.write_api()
    return write_api
```
If I run the above I am getting a `influxdb.exceptions.InfluxDBClientError: 401 {"code":"unauthorized","message":"Unauthorized"}`

I then wrote a simple python script to check:
```python
new_client = InfluxDBClient(url=url,
                            database=db,
                            token=token,
                            timeout=100000, retries=0, enable_gzip=False, username=user, password=pass,
                            org=org)  #These values would be gathered from a config.ini
query_api = new_client.query_api()

df = query_api.query_data_frame('from(bucket:db)'
                                '|> range(start: -200d)'
                                '|> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")'
                                '|> filter(fn: (r) => r._measurement == "test_result")'
                                '|> keep(columns: ["_time", "test", "run", "status_tag", "duration_sec", "version"])'
                                )
```
The above runs correctly and returns the correct results for the query. 

Am I missing something, or doing something wrong? 
__Expected behavior:__
I would expect to be able to connect to my Influxdb instance no matter the type of python script I am running (python or pytest).

__Actual behavior:__
I am not able to connect to my influxdb instance when running pytest but am able to when running python.

__Specifications:__
 - Client Version: 1.19.0
 - InfluxDB Version: 2.0.7
 - Platform: MacOS
 - pytest-influxdb: 0.0.32
 - influxdb: 5.3.1

**Comment by bednar** [comment]
Hi @rburchdish,

there isn't known issue with `pytest`, we also uses `pytest` in our test environment. 

It should be caused by wrong credentials. Can you share debug output of client?

```python
InfluxDBClient(url=influxdb_url, token=token, username=username, password=password, org=org, debug=True)
```

Regards

**Comment by rburchdish** [comment]
@bednar Thanks for the information. Looking through the debug I found that a rouge script was somehow running when my pytest script was kicked off. I have since deleted that file and the above error has gone away. I have run into two separate issues however:

1. A Threaded script that is kicked off when the test starts gives this error:
`from influxdb_client import InfluxDBClient
ModuleNotFoundError: No module named 'influxdb_client'`

2. I am unsure of how to pass my token variable through the pytest-influxdb plugin:
`reply: 'HTTP/1.1 401 Unauthorized\r\n'
header: Content-Type: application/json; charset=utf-8
header: X-Platform-Error-Code: unauthorized
header: Date: Fri, 16 Jul 2021 17:01:00 GMT
header: Content-Length: 48
InfluxDB Connection problem raised when sending test data to db.`

If this is the wrong platform to ask these questions please let me know.

Thanks for the help!

**Comment by bednar** [comment]
> 2. I am unsure of how to pass my token variable through the pytest-influxdb plugin:

You can pass your token via `InfluxDBClient` init parameter: `InfluxDBClient(url="http://localhost:8086", token="my-token", org="my-org")

**Comment by rburchdish** [comment]
@bednar My pytest is passing the influxdb_client params during start_up (see below):
```python
@pytest.fixture(scope="session", autouse=True)
def client_setup(influxdb_url, token, username, password, org, database):  # These values are coming from a conftest.py file
    new_client = InfluxDBClient(url=influxdb_url, token=token, username=username, password=password, org=org)
    write_api = new_client.write_api()
    return write_api
```

The issue is however that the previously working pytest-influxdb plugin (version 0.0.32) is no longer allowing me to connect after updating Influxdb to 2.0.7.

This plugin uses params passed during the execution of the test through CLI, see below for a sample:
```bash
pytest /Users/Desktop/Test/test_plugin.py --pytest-influxdb --influxdb_user=username --influxdb_password=password --influxdb_project=test --influxdb_run_id=1 --influxdb_version=1  -sv
```
When executing I am getting the following:
```bash
Traceback (most recent call last):
  File "/usr/local/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py", line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "/usr/local/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 304, in wrap_session
    config.hook.pytest_sessionfinish(
  File "/usr/local/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python3.9/site-packages/_pytest/terminal.py", line 813, in pytest_sessionfinish
    self.config.hook.pytest_terminal_summary(
  File "/usr/local/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/local/lib/python3.9/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python3.9/site-packages/pytest_influxdb/plugin.py", line 261, in pytest_terminal_summary
    suite_result_dto = SuiteResultDTO().get_suite_result_dto(terminalreporter, global_values, influxdb_components,
  File "/usr/local/lib/python3.9/site-packages/pytest_influxdb/suite_result_dto.py", line 121, in get_suite_result_dto
    self.merge_suite_result(global_values.get('merged'), influxdb_components,
  File "/usr/local/lib/python3.9/site-packages/pytest_influxdb/suite_result_dto.py", line 129, in merge_suite_result
    existing_suite_result = influxdb_components.get_results_by_run(db_measurement_name_for_suite, run_id_value)
  File "/usr/local/lib/python3.9/site-packages/pytest_influxdb/influxdb_components.py", line 15, in get_results_by_run
    return self.__client.query(
  File "/usr/local/lib/python3.9/site-packages/influxdb/client.py", line 521, in query
    response = self.request(
  File "/usr/local/lib/python3.9/site-packages/influxdb/client.py", line 332, in request
    response = self._session.request(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 627, in urlopen
    parsed_url = parse_url(url)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/url.py", line 394, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: //localhost:8086:8086/query?q=SELECT+%2A+FROM+suite_result+WHERE+run%3D%271%27&db=test
```
If this is the wrong group to be asking this question please let me know.

**Comment by rburchdish** [comment]
@bednar Thanks for the help! We can close this question out
