### ISSUE TITLE
Client exception that occurs on connection pool cleanup?

### ISSUE THREAD

**Issue by greenenvy** [influxdata/influxdb-client-python#381]
__Expected behavior:__
When defining the connection in my Django settings, on auto reload i'm getting some awkward exception which i'm not able to understand

Here is my Django setting part

`influxdb_client = InfluxDBClient(
    url="http://%s:%s" % (DATABASES['indluxDB']['HOST'], DATABASES['indluxDB']['PORT']),
    token=DATABASES['indluxDB']['TOKEN'],
    org=DATABASES['indluxDB']['ORG'],
)` 

__Actual behavior:__

Here is the exception i'm getting:

`Exception ignored in: <function InfluxDBClient.__del__ at 0x11a4e0940>
Traceback (most recent call last):
  File "/Users/ftninformatika/intelitynet/gsl/lib/python3.9/site-packages/influxdb_client/client/influxdb_client.py", line 354, in __del__
  File "/Users/ftninformatika/intelitynet/gsl/lib/python3.9/site-packages/influxdb_client/api_client.py", line 89, in __del__
  File "/Users/ftninformatika/intelitynet/gsl/lib/python3.9/site-packages/urllib3/poolmanager.py", line 222, in clear
  File "/Users/ftninformatika/intelitynet/gsl/lib/python3.9/site-packages/urllib3/_collections.py", line 95, in clear
TypeError: 'NoneType' object is not callable
Exception ignored in: <function ApiClient.__del__ at 0x1076ee280>
Traceback (most recent call last):
  File "/Users/ftninformatika/intelitynet/gsl/lib/python3.9/site-packages/influxdb_client/api_client.py", line 89, in __del__
  File "/Users/ftninformatika/intelitynet/gsl/lib/python3.9/site-packages/urllib3/poolmanager.py", line 222, in clear
  File "/Users/ftninformatika/intelitynet/gsl/lib/python3.9/site-packages/urllib3/_collections.py", line 95, in clear
TypeError: 'NoneType' object is not callable`

__Specifications:__
 - Client Version: 1.24.0
 - InfluxDB Version: 2.0.9
 - Platform: macOS Big Sur 11.5.2

**Comment by bednar** [comment]
Hi @greenenvy,

thanks for using our client.

I am not familiar with Django framework. Please share a small example project to simulate this exception.

Best Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
