### ISSUE TITLE
Write API is not working anymore?

### ISSUE THREAD

**Issue by ejri** [influxdata/influxdb-client-python#388]
Write API is not working anymore?

For whatever reason, I can't seem to be able to add anymore enteries (data points) to databases.
Tried manually adding values using "insert" and through the write API.

I'm running the same script that has been previously tested and working on 10+ devices.

**List the minimal actions needed to reproduce the behavior.**

Using 1.8.5 and 1.8.10 CLI: 
 

```
user = "username"
pass = "password"
db = "databasename"
host = "localhost"
port = 8086
body = [
                            {
                                "measurement": "measurement",
                                "tags": {
                                    "location": "location" ,
                            },
                                "fields": {
                                    "field_1": "string",
                                },
                                "time": time.time(),
                            }
                        ]

# connect to influx
client = InfluxDBClient(host, port, user, pass, db)

# write the measurement
client.write_points(body)
```
        
       
Using 2.0 CLI: 
 
```
_bucket = "databasename"
_org = ""
_token = "username:password"
_url = "http://localhost:8086/"
with InfluxDBClient(url=_url, token=_token, org=_org) as _client:

with _client.write_api(
    write_options=WriteOptions(
                batch_size=1_000,
                flush_interval=10_000,
                jitter_interval=2_000,
                retry_interval=5_000,
                max_retries=5,
                max_retry_delay=30_000,
                exponential_base=2,
                )
                ) as _write_client:

                _write_client.write(
                _bucket,
                _org,
               {
                                "measurement": "measurement",
                                "tags": {
                                    "location": "location" ,
                            },
                                "fields": {
                                    "field_1": "string",
                                },
                                "time": time.time(),
                            }
                )

```

Using "insert" command:
`
INSERT treasures,captain_id=pirate_king value=2 
`

__Expected behavior:__
Any of the above should (and have previously) added the values into the database.  

__Actual behavior:__
No values get added into databases. 
No errors. 
Tried uninstalling, reinstalling, etc. on two different raspberry pi's.

__Specifications:__
 - Client Version: latest
 - InfluxDB Version: 1.8.5, 1.8.10
 - Platform: raspberry pi Debian 
 - installation process: 

1. Everything up to date
`sudo apt update && sudo apt upgrade -y`
2. fetch Influxdb (latest stable version)
```
wget -qO- https://repos.influxdata.com/influxdb.key | sudo apt-key add -
source /etc/os-release
echo "deb https://repos.influxdata.com/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
```
3. Install 
`sudo apt update && sudo apt install -y influxdb`

4. (optional) run at boot:
```
sudo systemctl unmask influxdb.service
sudo systemctl start influxdb
sudo systemctl enable influxdb.service
```

**Comment by bednar** [comment]
Hi @ejri,

thanks for using our client.

> Using 1.8.5 and 1.8.10 CLI:
> 
> ```
> user = "username"
> pass = "password"
> db = "databasename"
> host = "localhost"
> port = 8086
> body = [
>                             {
>                                 "measurement": "measurement",
>                                 "tags": {
>                                     "location": "location" ,
>                             },
>                                 "fields": {
>                                     "field_1": "string",
>                                 },
>                                 "time": time.time(),
>                             }
>                         ]
> 
> # connect to influx
> client = InfluxDBClient(host, port, user, pass, db)
> 
> # write the measurement
> client.write_points(body)
> ```

This repository is determined for v2 client, please feel free to create a new issue in https://github.com/influxdata/influxdb-python.

> Using 2.0 CLI:
> 
> ```
> _bucket = "databasename"
> _org = ""
> _token = "username:password"
> _url = "http://localhost:8086/"
> with InfluxDBClient(url=_url, token=_token, org=_org) as _client:
> 
> with _client.write_api(
>     write_options=WriteOptions(
>                 batch_size=1_000,
>                 flush_interval=10_000,
>                 jitter_interval=2_000,
>                 retry_interval=5_000,
>                 max_retries=5,
>                 max_retry_delay=30_000,
>                 exponential_base=2,
>                 )
>                 ) as _write_client:
> 
>                 _write_client.write(
>                 _bucket,
>                 _org,
>                {
>                                 "measurement": "measurement",
>                                 "tags": {
>                                     "location": "location" ,
>                             },
>                                 "fields": {
>                                     "field_1": "string",
>                                 },
>                                 "time": time.time(),
>                             }
>                 )
> ```
> 

I've tested following piece of code again latest v1.9 Docker instance and everything works fine.

```python
import time

from influxdb_client import InfluxDBClient, WriteOptions

_bucket = "mydb"
_org = ""
_token = "username:password"
_url = "http://localhost:8086/"

with InfluxDBClient(url=_url, token=_token, org=_org, debug=True) as _client:
    with _client.write_api(
            write_options=WriteOptions(
                batch_size=1_000,
                flush_interval=10_000,
                jitter_interval=2_000,
                retry_interval=5_000,
                max_retries=5,
                max_retry_delay=30_000,
                exponential_base=2,
            )
    ) as _write_client:
        _write_client.write(
            _bucket,
            _org,
            {
                "measurement": "measurement",
                "tags": {
                    "location": "location",
                },
                "fields": {
                    "field_1": "string",
                },
                "time": time.time_ns(),
            }
        )

```

Can you share a debug output of the client? You can enable debug by:

```python
with InfluxDBClient(url=_url, token=_token, org=_org, debug=True) as _client:
```

What is a result for `time.time()`?

Regards

**Comment by ejri** [comment]
Hey, 

Thank you for getting back to me.

I pasted your code (changed credentials) and created a new database "mydb" and granted the username all privileges:

```
import time

from influxdb_client import InfluxDBClient, WriteOptions

_bucket = "mydb"
_org = ""
_token = "username:password"
_url = "http://localhost:8086/"

with InfluxDBClient(url=_url, token=_token, org=_org, debug=True) as _client:
    with _client.write_api(
            write_options=WriteOptions(
                batch_size=1_000,
                flush_interval=10_000,
                jitter_interval=2_000,
                retry_interval=5_000,
                max_retries=5,
                max_retry_delay=30_000,
                exponential_base=2,
            )
    ) as _write_client:
        _write_client.write(
            _bucket,
            _org,
            {
                "measurement": "measurement",
                "tags": {
                    "location": "location",
                },
                "fields": {
                    "field_1": "string",
                },
                "time": time.time_ns(),
            }
        )
```

This is the debug output (redacted username and password in line 3):

```
send: b'POST /api/v2/write?org=&bucket=mydb&precision=ns HTTP/1.1\r\nHost: localhost:8086\r\nAccept-Encoding: identity\r\nContent-Length: 66\r\nContent-Encoding: identity\r\nContent-Type: text/plain\r\nAccept: application/json\r\nAuthorization: Token [x]:[x]\r\nUser-Agent: influxdb-client-python/1.22.0\r\n\r\n'
send: b'measurement,location=location field_1="string" 1641238812575853359'
reply: 'HTTP/1.1 204 No Content\r\n'
header: Content-Type: application/json
header: Request-Id: f8c2a4d7-6ccc-11ec-8024-e45f012d58ee
header: X-Influxdb-Build: OSS
header: X-Influxdb-Version: 1.8.10
header: X-Request-Id: f8c2a4d7-6ccc-11ec-8024-e45f012d58ee
header: Date: Mon, 03 Jan 2022 19:40:14 GMT
```

**Comment by bednar** [comment]
> ```
> send: b'POST /api/v2/write?org=&bucket=mydb&precision=ns HTTP/1.1\r\nHost: localhost:8086\r\nAccept-Encoding: identity\r\nContent-Length: 66\r\nContent-Encoding: identity\r\nContent-Type: text/plain\r\nAccept: application/json\r\nAuthorization: Token [x]:[x]\r\nUser-Agent: influxdb-client-python/1.22.0\r\n\r\n'
> send: b'measurement,location=location field_1="string" 1641238812575853359'
> reply: 'HTTP/1.1 204 No Content\r\n'
> header: Content-Type: application/json
> header: Request-Id: f8c2a4d7-6ccc-11ec-8024-e45f012d58ee
> header: X-Influxdb-Build: OSS
> header: X-Influxdb-Version: 1.8.10
> header: X-Request-Id: f8c2a4d7-6ccc-11ec-8024-e45f012d58ee
> header: Date: Mon, 03 Jan 2022 19:40:14 GMT
> ```

`HTTP/1.1 204 No Content` - that means that your data are successfully written

**Comment by ejri** [comment]
Yeah, exactly! Yet, nothing got actually got uploaded to the database. It's completely empty.
<img width="718" alt="Screen Shot 2022-01-03 at 10 34 49 PM" src="https://user-images.githubusercontent.com/2915475/148018907-b20b6e90-b7a5-447b-9434-1f207e82590c.png">

**Comment by bednar** [comment]
How do you have retention policy set up?

**Comment by ejri** [comment]
Non-expiring... so all data should be written and retained, unless I delete them manually, etc..

**Comment by bednar** [comment]
Please, check query response via `python` by:

```python
import time

from influxdb_client import InfluxDBClient, WriteOptions

_bucket = "mydb"
_org = ""
_token = "username:password"
_url = "http://localhost:8086/"

with InfluxDBClient(url=_url, token=_token, org=_org, debug=True) as _client:
    with _client.write_api(
            write_options=WriteOptions(
                batch_size=1_000,
                flush_interval=10_000,
                jitter_interval=2_000,
                retry_interval=5_000,
                max_retries=5,
                max_retry_delay=30_000,
                exponential_base=2,
            )
    ) as _write_client:
        _write_client.write(
            _bucket,
            _org,
            {
                "measurement": "measurement",
                "tags": {
                    "location": "location",
                },
                "fields": {
                    "field_1": "string",
                },
                "time": time.time_ns(),
            }
        )

    tables = _client.query_api().query(f'from(bucket: \"{_bucket}\") |> range(start: -1d, stop: 1d)')
    print("\n\n=== Query ===\n\n")
    for record in tables[0].records:
        print(f'#{record.get_time()}: {record.get_field()}={record.get_value()}')

```

**Comment by ejri** [comment]
```
send: b'POST /api/v2/write?org=&bucket=mydb&precision=ns HTTP/1.1\r\nHost: localhost:8086\r\nAccept-Encoding: identity\r\nContent-Length: 66\r\nContent-Encoding: identity\r\nContent-Type: text/plain\r\nAccept: application/json\r\nAuthorization: Token username:password\r\nUser-Agent: influxdb-client-python/1.22.0\r\n\r\n'
send: b'measurement,location=location field_1="string" 1641286817809841355'
reply: 'HTTP/1.1 204 No Content\r\n'
header: Content-Type: application/json
header: Request-Id: bd4a88c1-6d3c-11ec-8005-e45f012d58ee
header: X-Influxdb-Build: OSS
header: X-Influxdb-Version: 1.8.10
header: X-Request-Id: bd4a88c1-6d3c-11ec-8005-e45f012d58ee
header: Date: Tue, 04 Jan 2022 09:00:18 GMT
send: b'POST /api/v2/query?org= HTTP/1.1\r\nHost: localhost:8086\r\nAccept-Encoding: identity\r\nContent-Length: 252\r\nAccept: application/json\r\nContent-Type: application/json\r\nAuthorization: Token username:password\r\nUser-Agent: influxdb-client-python/1.22.0\r\n\r\n'
send: b'{"extern": {"imports": [], "body": []}, "query": "from(bucket: \\"mydb\\") |> range(start: -1d, stop: 1d)", "dialect": {"header": true, "delimiter": ",", "annotations": ["datatype", "group", "default"], "commentPrefix": "#", "dateTimeFormat": "RFC3339"}}'
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: Content-Type: text/plain; charset=utf-8
header: Request-Id: bd5187f9-6d3c-11ec-8006-e45f012d58ee
header: X-Content-Type-Options: nosniff
header: X-Influxdb-Build: OSS
header: X-Influxdb-Version: 1.8.10
header: X-Request-Id: bd5187f9-6d3c-11ec-8006-e45f012d58ee
header: Date: Tue, 04 Jan 2022 09:00:18 GMT
header: Content-Length: 100
Traceback (most recent call last):
  File "/home/pi/Desktop/air_quality/upload_influx.py", line 37, in <module>
    tables = _client.query_api().query(f'from(bucket: \"{_bucket}\") |> range(start: -1d, stop: 1d)')
  File "/usr/local/lib/python3.7/dist-packages/influxdb_client/client/query_api.py", line 101, in query
    async_req=False, _preload_content=False, _return_http_data_only=False)
  File "/usr/local/lib/python3.7/dist-packages/influxdb_client/service/query_service.py", line 258, in post_query
    (data) = self.post_query_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python3.7/dist-packages/influxdb_client/service/query_service.py", line 353, in post_query_with_http_info
    urlopen_kw=urlopen_kw)
  File "/usr/local/lib/python3.7/dist-packages/influxdb_client/api_client.py", line 346, in call_api
    _preload_content, _request_timeout, urlopen_kw)
  File "/usr/local/lib/python3.7/dist-packages/influxdb_client/api_client.py", line 175, in __call_api
    _request_timeout=_request_timeout, **urlopen_kw)
  File "/usr/local/lib/python3.7/dist-packages/influxdb_client/api_client.py", line 393, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.7/dist-packages/influxdb_client/rest.py", line 311, in POST
    **urlopen_kw)
  File "/usr/local/lib/python3.7/dist-packages/influxdb_client/rest.py", line 254, in request
    raise ApiException(http_resp=r)
influxdb_client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Content-Type': 'text/plain; charset=utf-8', 'Request-Id': 'bd5187f9-6d3c-11ec-8006-e45f012d58ee', 'X-Content-Type-Options': 'nosniff', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '1.8.10', 'X-Request-Id': 'bd5187f9-6d3c-11ec-8006-e45f012d58ee', 'Date': 'Tue, 04 Jan 2022 09:00:18 GMT', 'Content-Length': '100'})
HTTP response body: b'Flux query service disabled. Verify flux-enabled=true in the [http] section of the InfluxDB config.\n'
```

**Comment by bednar** [comment]
Here is a doc how to enable Flux queries - https://docs.influxdata.com/influxdb/v1.8/flux/installation/#enable-flux

**Comment by ejri** [comment]
Ok, that's interesting. It's being logged, but I can't see it?

```
send: b'POST /api/v2/write?org=&bucket=mydb&precision=ns HTTP/1.1\r\nHost: localhost:8086\r\nAccept-Encoding: identity\r\nContent-Length: 66\r\nContent-Encoding: identity\r\nContent-Type: text/plain\r\nAccept: application/json\r\nAuthorization: Token username:password\r\nUser-Agent: influxdb-client-python/1.22.0\r\n\r\n'
send: b'measurement,location=location field_1="string" 1641287760513040770'
reply: 'HTTP/1.1 204 No Content\r\n'
header: Content-Type: application/json
header: Request-Id: ef6a95eb-6d3e-11ec-8002-e45f012d58ee
header: X-Influxdb-Build: OSS
header: X-Influxdb-Version: 1.8.10
header: X-Request-Id: ef6a95eb-6d3e-11ec-8002-e45f012d58ee
header: Date: Tue, 04 Jan 2022 09:16:01 GMT
send: b'POST /api/v2/query?org= HTTP/1.1\r\nHost: localhost:8086\r\nAccept-Encoding: identity\r\nContent-Length: 252\r\nAccept: application/json\r\nContent-Type: application/json\r\nAuthorization: Token username:password\r\nUser-Agent: influxdb-client-python/1.22.0\r\n\r\n'
send: b'{"extern": {"imports": [], "body": []}, "query": "from(bucket: \\"mydb\\") |> range(start: -1d, stop: 1d)", "dialect": {"header": true, "delimiter": ",", "annotations": ["datatype", "group", "default"], "commentPrefix": "#", "dateTimeFormat": "RFC3339"}}'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: text/csv; charset=utf-8
header: Request-Id: ef732ef1-6d3e-11ec-8003-e45f012d58ee
header: X-Influxdb-Build: OSS
header: X-Influxdb-Version: 1.8.10
header: X-Request-Id: ef732ef1-6d3e-11ec-8003-e45f012d58ee
header: Date: Tue, 04 Jan 2022 09:16:01 GMT
header: Transfer-Encoding: chunked


=== Query ===


#2022-01-03 19:40:12.575853+00:00: field_1=string
#2022-01-04 09:00:17.809841+00:00: field_1=string
#2022-01-04 09:10:03.591317+00:00: field_1=string
#2022-01-04 09:11:08.140050+00:00: field_1=string
#2022-01-04 09:16:00.513040+00:00: field_1=string
```


```
pi@raspberrypi:~/Desktop $ influx
Connected to http://localhost:8086 version 1.8.10
InfluxDB shell version: 1.8.10
> use mydb
Using database mydb
> select * from mydb
> 
```

**Comment by bednar** [comment]
Hard to say where is a glitch...

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
