### ISSUE TITLE
Delete API error

### ISSUE THREAD

**Issue by AnSchil** [influxdata/influxdb-client-python#410]
__Steps to reproduce:__
I'm running InfluxDB on a Raspberry Pi and try to delete data from a bucket. Here is my code snippet:

`start = "1970-01-01T00:00:00Z"`
`stop = datetime.utcnow`
 `client.delete_api().delete(start, stop, "", bucket=bucket_iot, org=org)`

It throws the following error:
                                                            
2022-02-18 16:39:46,027 Fehler aufgetreten
Traceback (most recent call last):
  File "/usr/src/app/retry.py", line 23, in retry
    f()
  File "/usr/src/app/send_message.py", line 79, in main
    client.delete_api().delete(start, stop, "", bucket=bucket_iot, org=org)
  File "/usr/local/lib/python3.10/site-packages/influxdb_client/client/delete_api.py", line 35, in delete
    return self._service.post_delete(delete_predicate_request=predicate_request, bucket=bucket, org=org)
  File "/usr/local/lib/python3.10/site-packages/influxdb_client/service/delete_service.py", line 58, in post_delete
    (data) = self.post_delete_with_http_info(delete_predicate_request, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.10/site-packages/influxdb_client/service/delete_service.py", line 142, in post_delete_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.10/site-packages/influxdb_client/api_client.py", line 341, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.10/site-packages/influxdb_client/api_client.py", line 162, in __call_api
    body = self.sanitize_for_serialization(body)
  File "/usr/local/lib/python3.10/site-packages/influxdb_client/api_client.py", line 232, in sanitize_for_serialization
    return {key: self.sanitize_for_serialization(val)
  File "/usr/local/lib/python3.10/site-packages/influxdb_client/api_client.py", line 232, in <dictcomp>
    return {key: self.sanitize_for_serialization(val)
  File "/usr/local/lib/python3.10/site-packages/influxdb_client/api_client.py", line 229, in sanitize_for_serialization
    for attr, _ in six.iteritems(obj.openapi_types)
AttributeError: 'builtin_function_or_method' object has no attribute 'openapi_types'

__Expected behavior:__
Measurements in the bucket should get deleted.

__Actual behavior:__
Error which I personally can not trace back.

__Specifications:__
 - Client Version: 1.26.0
 - InfluxDB Version: 2.1
 - Platform: armv7 with Python 3.10 Docker Image

**Comment by AnSchil** [comment]
Fixed it by changing datetime.utcnow() to datetime.today().

Somehow datetime.utcnow() does not seem to get caught by the serializer (it should be a datetime object) and ends up in the else statement where it can't be processed.

**Comment by bednar** [comment]
Hi @AnSchil,

thanks for using our client.

> body = self.sanitize_for_serialization(body)
> File "/usr/local/lib/python3.10/site-packages/influxdb_client/api_client.py", line 232, in sanitize_for_serialization
> return {key: self.sanitize_for_serialization(val)
> File "/usr/local/lib/python3.10/site-packages/influxdb_client/api_client.py", line 232, in 
> return {key: self.sanitize_for_serialization(val)
> File "/usr/local/lib/python3.10/site-packages/influxdb_client/api_client.py", line 229, in sanitize_for_serialization
> for attr, _ in six.iteritems(obj.openapi_types)
> AttributeError: 'builtin_function_or_method' object has no attribute 'openapi_types'

This is caused by missing brackets in your script. Try to use `stop = datetime.utcnow()` instead of `stop = datetime.utcnow`.

Regards

**Comment by AnSchil** [comment]
Thanks for the heads up. 
Sometimes it's the little things. I guess when switching from utcnow() to today() I corrected my own mistake. Stupid :D

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
