### ISSUE TITLE
Asynchronous Permission denied

### ISSUE THREAD

**Issue by LydiaLu** [influxdata/influxdb-client-python#468]
I can use the synchronous way but fail in asynchronous way. (PS: I use the docker run influxdb as db server)
The Code is :
```
import asyncio
from influxdb_client.client.influxdb_client_async import InfluxDBClientAsync

async def main():
    async with InfluxDBClientAsync(url=url, token=token, org=org, debug=True) as client:
        ready = await client.ping()
        print(f"InfluxDB: {ready}")


if __name__ == "__main__":
    asyncio.run(main())
```

Result:
>>> Request: 'GET http://127.0.0.1:8086/ping'
>>> Headers: '<CIMultiDict('Authorization': 'Token': '..............', 'User-Agent': 'influxdb-client-python/1.30.0', 'Content-Type': 'application/json')>'
<<< Response: 502
<<< Headers: '<CIMultiDictProxy('Content-Type': 'text/html')>
<<< Body: <html><body><h1>502 Permission denied</h1><p><a href='http://cntlm.sf.net/'>Cntlm</a> proxy failed to complete the request.</p></body></html>
DEBUG:influxdb_client.client.influxdb_client_async:Unexpected error during /ping: (502)
Reason: Permission denied
HTTP response headers: <CIMultiDictProxy('Content-Type': 'text/html')>
HTTP response body: b"<html><body><h1>502 Permission denied</h1><p><a href='http://cntlm.sf.net/'>Cntlm</a> proxy failed to complete the request.</p></body></html>"

Traceback (most recent call last):
  File "/Users/Desktop/Code/ATR/influxdb_test.py", line 151, in <module>
    asyncio.run(main())
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/Desktop/Code/ATR/influxdb_test.py", line 146, in main
    ready = await client.ping()
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/influxdb_client_async.py", line 187, in ping
    raise ex
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/influxdb_client_async.py", line 183, in ping
    await ping_service.get_ping_async()
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/ping_service.py", line 103, in get_ping_async
    return await self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_async/api_client.py", line 173, in __call_api
    response_data = await self.request(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_async/rest.py", line 235, in GET
    return (await self.request("GET", url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/_async/rest.py", line 228, in request
    raise ApiException(http_resp=r)
influxdb_client.rest.ApiException: (502)
Reason: Permission denied
HTTP response headers: <CIMultiDictProxy('Content-Type': 'text/html')>
HTTP response body: b"<html><body><h1>502 Permission denied</h1><p><a href='http://cntlm.sf.net/'>Cntlm</a> proxy failed to complete the request.</p></body></html>"

Please help if you have any comments.

**Comment by bednar** [comment]
Hi @LydiaLu,

thanks for using our client.

It looks like problem with your `[Cntlm](http://cntlm.sf.net/)` proxy. 

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
