### ISSUE TITLE
SSL Failure

### ISSUE THREAD

**Issue by pavarott** [influxdata/influxdb-client-python#529]
Hey Guys I've been looking through the isues with errors from the SSL but had every time this error with each solution.
I'm working on a Linux notebook
my code:

`import influxdb_client
import certifi
import ssl
from influxdb_client.client.write_api import SYNCHRONOUS
import urllib3
"""
http = urllib3.PoolManager(cert_reqs=ssl.CERT_REQUIRED)
resp = http.request('GET',"myurl")
print(resp.headers)
"""
bucket = "lab"
org = "org"
token = "token"

ssl_ca_certi = certifi.where()

# Store the URL of your InfluxDB instance
url='mydomain.com:8086'
client = influxdb_client.InfluxDBClient(
    url=url,
    org=org,
    token=token,
    verify_ssl=True,
    ssl_ca_cert=ssl_ca_certi
)

# Query script
query_api = client.query_api()
query = 'from(bucket: "bucket")' \
  '|> range(start: -4h)' \
  '|> filter(fn: (r) => r._measurement == "measure")' \
  '|> filter(fn: (r) => r._field == "P")' \
  '|> aggregateWindow(every: 1m, fn: mean, createEmpty: false)' \
  '|> yield(name: "mean")'

result = query_api.query(org=org, query=query)

results = []
for table in result:
    for record in table.records:
        results.append((record.get_field(), record.get_value()))

print(results)`

the error:
Traceback (most recent call last):
  File "/home/chief/Downloads/query.py", line 36, in <module>
    result = query_api.query(org=org, query=query)
  File "/home/chief/.local/lib/python3.9/site-packages/influxdb_client/client/query_api.py", line 203, in query
    response = self._query_api.post_query(org=org, query=self._create_query(query, self.default_dialect, params),
  File "/home/chief/.local/lib/python3.9/site-packages/influxdb_client/service/query_service.py", line 281, in post_query
    (data) = self.post_query_with_http_info(**kwargs)  # noqa: E501
  File "/home/chief/.local/lib/python3.9/site-packages/influxdb_client/service/query_service.py", line 307, in post_query_with_http_info
    return self.api_client.call_api(
  File "/home/chief/.local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 343, in call_api
    return self.__call_api(resource_path, method,
  File "/home/chief/.local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api
    response_data = self.request(
  File "/home/chief/.local/lib/python3.9/site-packages/influxdb_client/_sync/api_client.py", line 388, in request
    return self.rest_client.POST(url,
  File "/home/chief/.local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 311, in POST
    return self.request("POST", url,
  File "/home/chief/.local/lib/python3.9/site-packages/influxdb_client/_sync/rest.py", line 243, in request
    raise ApiException(status=0, reason=msg)
influxdb_client.rest.ApiException: (0)
Reason: SSLError
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

**Comment by bednar** [comment]
Hi @pavarott,

thanks for using our client.

Do you use local InfluxDB OSS or InfluxDB Cloud? Do you use self signed certificate?

Regards

**Comment by maddencs** [comment]
I resolved this issue on my Mac using the following command(update the Python path to your appropriate version):
```
open /Applications/Python\ 3.9/Install\ Certificates.command
```

**Comment by pavarott** [comment]
Hi @bednar 

Sorry I missed the mail.

I'm using InfluxDB OSS in a Docker container. 

I think so my friend set up the virtual machine and I'm not sure if I have to use it.

Regards

**Comment by bednar** [comment]
@pavarott if you are running local instance in Docker then you can disable verify SSL by: `verify_ssl=False`
