### ISSUE TITLE
Error executing multiprocessing example

### ISSUE THREAD

**Issue by apogre** [influxdata/influxdb-client-python#578]
examples/import_data_set_multiprocessing.py

https://github.com/influxdata/influxdb-client-python/blob/master/examples/import_data_set_multiprocessing.py

Error executing multiprocessing example are reactivex upgrade.

```
 Unexpected error: 'Future' object is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/reactivex/observable/observable.py", line 125, in set_disposable
    subscriber = self._subscribe_core(auto_detach_observer, scheduler)
  File "/usr/local/lib/python3.9/site-packages/reactivex/observable/observable.py", line 49, in _subscribe_core
    return self._subscribe(observer, scheduler) if self._subscribe else Disposable()
  File "/usr/local/lib/python3.9/site-packages/reactivex/observable/fromiterable.py", line 31, in subscribe
    iterator = iter(iterable)
TypeError: 'Future' object is not iterable
```

**Comment by mecod** [comment]
Same error.
After change 
`ops.flat_map(lambda rows: executor.submit(parse_rows, rows, content_length)))`
to
`ops.map(lambda rows: executor.submit(parse_rows, rows, content_length)))`
it works now.

**Comment by bednar** [comment]
@mecod, @apogre thanks for report this. We will take a look.
