### ISSUE TITLE
ModuleNotFoundError: import of urllib3.response halted; None in sys.modules

### ISSUE THREAD

**Issue by dcl-lily** [influxdata/influxdb-client-python#581]
### Specifications

* Client Version: 1.36.1
* InfluxDB Version: v2.6.1
* Platform: mac os 13.4
* Python Model: urllib3==2.0.2

### Code sample to reproduce problem

```python
point = influx_connect.point.measurement("rabbit_queues")
point.tag('name', one.get("name"))
point.field('ready', int(one.get('messages_ready', 0)))
point.field('un_acked', float(one.get('messages_unacknowledged', 0)))
message_stats = one.get('message_stats', {})
point.field('queue_in_per_second', float(message_stats.get('publish_details', {}).get('rate', 0)))
point.field('queue_out_per_second', float(message_stats.get('deliver_get_details', {}).get('rate', 0)))
point.field('queue_ack_per_second', float(message_stats.get('ack_details', {}).get('rate', 0)))
influx_connect.write_all(point)
```

### Expected behavior

No abnormal error message is reported

### Actual behavior

```
Exception ignored in: <function InfluxDBClient.__del__ at 0x10c04cd30>
Traceback (most recent call last):
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/influxdb_client/client/influxdb_client.py", line 319, in __del__
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/influxdb_client/_sync/api_client.py", line 84, in __del__
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/influxdb_client/_sync/api_client.py", line 662, in _signout
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/influxdb_client/service/signout_service.py", line 51, in post_signout
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/influxdb_client/service/signout_service.py", line 72, in post_signout_with_http_info
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/influxdb_client/_sync/api_client.py", line 343, in call_api
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/influxdb_client/_sync/api_client.py", line 388, in request
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/influxdb_client/_sync/rest.py", line 311, in POST
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/influxdb_client/_sync/rest.py", line 186, in request
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/urllib3/_request_methods.py", line 118, in request
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/urllib3/_request_methods.py", line 217, in request_encode_body
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/urllib3/poolmanager.py", line 433, in urlopen
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/urllib3/connection.py", line 451, in getresponse
ModuleNotFoundError: import of urllib3.response halted; None in sys.modules
Exception ignored in: <function ApiClient.__del__ at 0x10c0b01f0>
Traceback (most recent call last):
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/influxdb_client/_sync/api_client.py", line 84, in __del__
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/influxdb_client/_sync/api_client.py", line 662, in _signout
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/influxdb_client/service/signout_service.py", line 51, in post_signout
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/influxdb_client/service/signout_service.py", line 72, in post_signout_with_http_info
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/influxdb_client/_sync/api_client.py", line 343, in call_api
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/influxdb_client/_sync/api_client.py", line 388, in request
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/influxdb_client/_sync/rest.py", line 311, in POST
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/influxdb_client/_sync/rest.py", line 186, in request
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/urllib3/_request_methods.py", line 118, in request
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/urllib3/_request_methods.py", line 217, in request_encode_body
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/urllib3/poolmanager.py", line 433, in urlopen
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
  File "/Users/admin/PycharmProjects/rabbit_monitor/venv/lib/python3.10/site-packages/urllib3/connection.py", line 451, in getresponse
ModuleNotFoundError: import of urllib3.response halted; None in sys.modules
```

### Additional info

Try to downgrading urllib3 to 1.28 with no exception， Although the urllib3==2.0.2 reported error, but the data was written to the db

**Comment by powersj** [comment]
Hi,

What version of Python are you running? 
Can you please provide the output of `pip list`?
Can you please provide an actual example to reproduce the issue?

Your code snippet calls `write_all`, but you did not show how you created that write API client.

```
❯ pip list
Package           Version
----------------- --------
certifi           2023.5.7
ciso8601          2.3.0
influxdb-client   1.36.1
pip               23.1.2
python-dateutil   2.8.2
reactivex         4.0.4
setuptools        67.7.2
six               1.16.0
typing_extensions 4.6.3
urllib3           2.0.3
wheel             0.40.0
```

```python
#!/usr/bin/env python3
"""Demonstrate a basic synchronous write."""
from influxdb_client import InfluxDBClient
from influxdb_client.client.exceptions import InfluxDBError
from influxdb_client.client.write_api import SYNCHRONOUS

with InfluxDBClient.from_config_file("config.toml") as client:
    with client.write_api(write_options=SYNCHRONOUS) as writer:
        try:
            writer.write(bucket="my-bucket", record="cpu,core=0 temp=25.3 1657729063")
        except InfluxDBError as e:
            print(e)
```

I was able to use the following to successfully write.

**Comment by dcl-lily** [comment]
└─[$]> python3 --version 
Python 3.10.5

└─[$]> pip list 
Package            Version
------------------ --------
certifi            2023.5.7
charset-normalizer 3.1.0
idna               3.4
influxdb-client    1.36.1
pip                23.1.2
python-dateutil    2.8.2
python-dotenv      1.0.0
reactivex          4.0.4
requests           2.30.0
setuptools         65.5.1
six                1.16.0
typing_extensions  4.5.0
urllib3            2.0.2
wheel              0.38.4

```python
#db.py

class InfluxDB:
    def __init__(self, info_db_url='http://127.0.0.1:8086', token=None, bucket='infra',
                 org='infra', username='admin', password='admin@123',measurement="default"):
        self.measurement = measurement
        self.point = Point
        if token is None:
            influx_client = InfluxDBClient(url=info_db_url, username=username, password=password)
        else:
            influx_client = InfluxDBClient(url=info_db_url, token=token)

        self.write_api = influx_client.write_api(write_options=SYNCHRONOUS)
        self.query_api = influx_client.query_api()
        self.delete_api = influx_client.delete_api()
        self.bucket = bucket
        self.org = org

    def write_all(self, point):
        try:
            self.write_api.write(bucket=self.bucket, org=self.org, record=point)
        except Exception as e:
            print(f"数据写入数据库失败{e.args}") 

#main.py
from db import InfluxDB
influx_connect = InfluxDB(f"http://{influx_host}:{influx_port}", influx_token, influx_bucket,
                              influx_org, influx_username, influx_password)
````

**Comment by dcl-lily** [comment]
```python
# demo 
import os
from influxdb_client import InfluxDBClient
from dotenv import load_dotenv
load_dotenv()
from influxdb_client.client.exceptions import InfluxDBError
from influxdb_client.client.write_api import SYNCHRONOUS
influx_host = os.environ.get("INFLUX_HOST", "127.0.0.1")
influx_port = os.environ.get("INFLUX_PORT", 8086)
influx_token = os.environ.get("INFLUX_TOKEN", None)
influx_bucket = os.environ.get("INFLUX_BUCKET", "infra")
influx_org = os.environ.get("INFLUX_ORG", "infra")
influx_username = os.environ.get("INFLUX_USERNAME", "admin")
influx_password = os.environ.get("INFLUX_PASSWORD", "admin@123")

with InfluxDBClient(url=f"http://{influx_host}:{influx_port}", username=influx_username, password=influx_password) as client:
    with client.write_api(write_options=SYNCHRONOUS) as writer:
        try:
            writer.write(bucket=influx_bucket, record="cpu,core=0 temp=25.3", org=influx_org)
        except InfluxDBError as e:
            print(e)
```

demo code execution without error message

**Comment by powersj** [comment]
> demo code execution without error message

Right because you are using a context manager to correctly close the client after usage. You are not doing that in your custom class.

**Comment by dcl-lily** [comment]
Thank you. Problem solved
